---
kind: Service
apiVersion: v1
metadata:
  name: demoservice
spec:
  selector:
    app: demo
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demodeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: kyawbo/demo-v1.0.0
          ports:
            - containerPort: 8080